
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BanqueS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:2233/?wsdl")
public class BanqueS
    extends Service
{

    private static final URL BANQUES_WSDL_LOCATION;
    private static final WebServiceException BANQUES_EXCEPTION;
    private static final QName BANQUES_QNAME = new QName("http://ws/", "BanqueS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2233/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUES_WSDL_LOCATION = url;
        BANQUES_EXCEPTION = e;
    }

    public BanqueS() {
        super(__getWsdlLocation(), BANQUES_QNAME);
    }

    public BanqueS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUES_QNAME, features);
    }

    public BanqueS(URL wsdlLocation) {
        super(wsdlLocation, BANQUES_QNAME);
    }

    public BanqueS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUES_QNAME, features);
    }

    public BanqueS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUES_EXCEPTION!= null) {
            throw BANQUES_EXCEPTION;
        }
        return BANQUES_WSDL_LOCATION;
    }

}
